version: '3.4'

services:
  rabbitmq1:
    image: bitnami/rabbitmq
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      - RABBITMQ_USERNAME=rabbitmquser
      - RABBITMQ_PASSWORD=rabbitmqpassword
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq1
      - RABBITMQ_ERL_COOKIE=rabbitmq-secret
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq-network
    mem_limit: 512m

  rabbitmq2:
    image: bitnami/rabbitmq
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      - RABBITMQ_USERNAME=rabbitmquser
      - RABBITMQ_PASSWORD=rabbitmqpassword
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq2
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmq1
      - RABBITMQ_ERL_COOKIE=rabbitmq-secret
    ports:
      - 15673:15672
      - 5673:5672
    networks:
      - rabbitmq-network
    mem_limit: 512m

  rabbitmq3:
    image: bitnami/rabbitmq
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      - RABBITMQ_USERNAME=rabbitmquser
      - RABBITMQ_PASSWORD=rabbitmqpassword
      - RABBITMQ_NODE_TYPE=queue-ram
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq3
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmq1
      - RABBITMQ_ERL_COOKIE=rabbitmq-secret
    ports:
      - 15674:15672
      - 5674:5672
    networks:
      - rabbitmq-network
    mem_limit: 512m

networks:
  rabbitmq-network:
